name: evolution101
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - blinker=1.7.0
  - docutils=0.20.1
  - feedgenerator=2.1.0
  - jinja2=3.1.4
  - markdown=3.6
  - markupsafe=2.1.5
  - pelican=4.9.1
  - pip=24.2
  - pygments=2.18.0
  - python-dateutil=2.9.0.post0
  - pytz=2024.2
  - setuptools=75.1.0
  - six=1.16.0
  - unidecode=1.3.7
  - wheel=0.44.0
